name: Check for updated Factorio version

on:
  schedule:
    - cron: "0 6 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-for-updated-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm ci
      - run: npm run download-latest-api-jsons
      - name: record change
        if: success()
        run: echo "updated=true" >> $GITHUB_OUTPUT
      - name: record failure
        if: failure()
        run: echo "updated=false" >> $GITHUB_OUTPUT
  
  create-pr-for-updated-factorio-version:
    runs-on: ubuntu-latest
    needs: check-for-updated-version
    if: ${{ needs.check-for-updated-version.outputs.updated == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm ci
      - run: npm run download-latest-api-jsons
      - name: Get current version
        run: echo "FACTORIO_VERSION=$(npx tsx ./scripts/get-current-version.ts )" >> $GITHUB_ENV
      - run: npm run clean
      - run: npm run generate
      - run: npm run new-version-changelog
      - run: npm version minor
      - name: Create Pull Request
#        uses: peter-evans/create-pull-request@v6
#        with:
#          commit-message: "Update to Factorio API version ${{ env.FACTORIO_VERSION }}"
#          title: "Update to Factorio API version ${{ env.FACTORIO_VERSION }}"
        run: echo "This would create a PR for Factorio API version ${{ env.FACTORIO_VERSION }}"
